<!doctype html><html lang=en dir=auto><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>[TIL] Python basic 17: try ~ exception | Jeha00 DevLog</title><meta name=keywords content="TIL,python"><meta name=description content="Error의 종류와 예외 처리문에 대해 알아보고, 일부러 에러를 일으키는 이유와 방법에 대해 알아보겠다."><meta name=author content="Jeha00"><link rel=canonical href=http://jeha00.github.io/post/python_basic/python_basic_17_try_exception/><meta name=google-site-verification content="XYZabc"><meta name=yandex-verification content="XYZabc"><meta name=msvalidate.01 content="XYZabc"><link crossorigin=anonymous href=/assets/css/stylesheet.min.1e44d58192cbf6d7a4eb649bc43dbc3d4cc432677e5d8adc69b08c34cbe461ac.css integrity="sha256-HkTVgZLL9tek62SbxD28PUzEMmd+XYrcabCMNMvkYaw=" rel="preload stylesheet" as=style><link rel=icon href=http://jeha00.github.io/favicon.ico><link rel=icon type=image/png sizes=16x16 href=http://jeha00.github.io/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=http://jeha00.github.io/favicon-32x32.png><link rel=apple-touch-icon href=http://jeha00.github.io/apple-touch-icon.png><link rel=mask-icon href=http://jeha00.github.io/safari-pinned-tab.svg><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><meta name=generator content="Hugo 0.98.0"><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--hljs-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><script type=application/javascript>var doNotTrack=!1;doNotTrack||(function(e,o,i,a,t,n,s){e.GoogleAnalyticsObject=t,e[t]=e[t]||function(){(e[t].q=e[t].q||[]).push(arguments)},e[t].l=1*new Date,n=o.createElement(i),s=o.getElementsByTagName(i)[0],n.async=1,n.src=a,s.parentNode.insertBefore(n,s)}(window,document,"script","https://www.google-analytics.com/analytics.js","ga"),ga("create","UA-123-45","auto"),ga("send","pageview"))</script><meta property="og:title" content="[TIL] Python basic 17: try ~ exception"><meta property="og:description" content="Error의 종류와 예외 처리문에 대해 알아보고, 일부러 에러를 일으키는 이유와 방법에 대해 알아보겠다."><meta property="og:type" content="article"><meta property="og:url" content="http://jeha00.github.io/post/python_basic/python_basic_17_try_exception/"><meta property="og:image" content="http://jeha00.github.io/47"><meta property="article:section" content="post"><meta property="article:published_time" content="2022-03-03T01:33:28+09:00"><meta property="article:modified_time" content="2022-03-03T01:33:28+09:00"><meta property="og:site_name" content="JeHa00 DevLog"><meta name=twitter:card content="summary_large_image"><meta name=twitter:image content="http://jeha00.github.io/47"><meta name=twitter:title content="[TIL] Python basic 17: try ~ exception"><meta name=twitter:description content="Error의 종류와 예외 처리문에 대해 알아보고, 일부러 에러를 일으키는 이유와 방법에 대해 알아보겠다."><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Posts","item":"http://jeha00.github.io/post/"},{"@type":"ListItem","position":2,"name":"[TIL] Python basic 17: try ~ exception","item":"http://jeha00.github.io/post/python_basic/python_basic_17_try_exception/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"[TIL] Python basic 17: try ~ exception","name":"[TIL] Python basic 17: try ~ exception","description":"Error의 종류와 예외 처리문에 대해 알아보고, 일부러 에러를 일으키는 이유와 방법에 대해 알아보겠다.","keywords":["TIL","python"],"articleBody":"1. Exception(예외) and Error(에러)의 차이점  Exception(예외) 와 Error(에러)에 대해 설명하겠다. 예외는 무엇이고 에러는 무엇이다라고 외우진 말자. 예외를 에러의 범주에 포함하기도 하기 때문이다. 다만, 예외와 에러에 대한 틀을 잡기 위해 설명한다.   Exception(예외)는 우리가 작성한 로직에서 비정상적으로 발생한 사건(event)이다.  예외에는 예측이 가능한 예외와 예측이 불가능한 예외로 나눠진다. 예측 가능한 예외의 경우는 id 입력을 생각해보자. 영어로 입력해야하는데, 한글을 입력했을 경우 예외가 발생한다. 예측 불가능한 예외의 경우는 메모리의 용량이 부족해서, OS에서 발생한 에러, 하드웨어적인 에러 등등이 해당된다.   이 예외와 에러를 잘 처리해야 내가 의도한대로 작동하는 어플리케이션을 만들 수 있다.   2. Error의 종류 2.1 SyntaxError: 문법 오류 # 조건문의 헤더에 콜론(:)을 하지 않아 발생했다.  print('error')  print('error')  if True  pass SyntaxError: invalid syntax 2.2 TypeError: 자료형에 맞지 않는 연산을 수행하여 발생하는 오류  x = [1,2]  y = (1,2)  z = 'test'  # list와 tuple은 합칠 수 없다.  print(x + y) TypeError: can only concatenate list (not \"tuple\") to list  # string과 list는 합칠 수 없다.  print(x + z) TypeError: can only concatenate list (not \"str\") to list  # tuple과 string은 합칠 수 없다.  print(y + z) TypeError: can only concatenate list (not \"str\") to list 2.3 NameError: 참조가 없을 때 발생하는 오류  a = 10  b = 15  print(c) NameError: name 'c' is not defined 2.4 IndexError: index가 존재하지 않아 발생하는 오류  x = [50, 70, 90]  print(x[1]) 70  print(x[4] IndexError: list index out of range  # 알고리즘에서 op을 사용할 때 발생할 수 있는 에러  print(x.pop()) 50  print(x.pop()) 70  print(x.pop()) 90  print(x.pop()) IndexError: pop from empty list 2.5 ValueError: 참조값이 없을 때 발생하는 오류  x = [10, 50, 90]  x.remove(50)  print(x) [10, 90]   x.remove(200) ValueError: list.remove(x): x not in list 2.6 KeyError: 해당되는 key가 없을 때 발생하는 오류  # `key` 값으로 `value` 값을 출력할 때는 `.get()` 함수를 사용한다.  x = {'A': 'apple', 'B': 'Banana', 'C': 'coffee'}  print(x['D']) KeyError: 'D'  print(x.get('D')) None 2.7 AttributeError: 모듈, 클래스에 있는 잘못된 속성을 사용하여 발생한 오류  import time  print(time.time2()) AttributeError: module 'time' has no attribute 'time2' 2.8 FileNotFoundError: 파일을 찾을 수 없을 때 발생하는 오류  f = open('test.txt') FileNotFoundError: [Errno 2] No such file or directory: 'test.txt' 2.9 ZeroDivisionError: 0으로 나눠서 발생하는 오류  print(100 / 0) ZeroDivisionError: division by zero  3. 예외 처리 (try ~ exception)  try: 에러가 발생할 가능성이 있는 코드 실행  이 에러는 내 코드가 정확해도, 방문한 사이트 서버나 여러 프로그램이 외부와 연결될 때, 문제가 있을 수 있기 때문이다. 그래서 외부적으로 문제가 발생해도 try ~ except로 대비한다.   except 에러명 1~n:  error가 발생했을 때 잡아내어 다음 코드로 넘어가도록 해준다. 여러 개 가능하다. 어떤 Error만 잡을지 정할 수 있다. 모든 error 잡아내기  except Exception:은 모든 예외의 부모격이라 모든 error를 잡아낸다. except: 또한, 모든 error을 잡아낸다. 하지만, 정확히 어떤 error가 발생했는지 알 수 없다. 정확히 어떤 error가 발생했는지 알아야 로그를 남길 때 정확히 남길 수 있다.   예제 3에서처럼 예제 2에서 alias를 줘서 except Exception as e 와 print(e) 을 사용하여, 대략적인 error 내용을 확인하여 출력하도록 할 수 있다.   else: try block에 에러가 없을 경우 실행한다.  정상적으로 흘러갈 때 실행된다. for ~ else 에서도 for문에 break를 만나지 않으면 else가 실행했듯이, except를 만나지 않으면 실행된다.   finally: 에러발생 유무와 상관없이 무조건 실행된다.  error 발생 유무에 상관없이 항상 실행해줘야 하는 구문으로 finally를 사용한다. 예를 들어 error가 발생했을 경우, 연결된 메모리를 끊어줘야 메모리가 새지 않기 때문에 finally를 통해서 실행한다.    ## 예제 1 ## error 발생하지 않는 코드  name = ['Kim', 'Lee', 'Park']  print(name.index('Kim'))  try :  z = 'Kim'  x = name.index(z)  print('{} Found it! {} in name'.format(z, x + 1))  # error 중 ValueError 만 잡는다. # error 처리 시, 이렇게 error의 정확한 유형대로 잡아내느 것이 제일 좋은 case다.  except ValueError:  print('Not found it! - Occurred ValueError!')  # error가 발생되지 않았으므로 else 구문이 작동된다.  else:  print('Ok! else.')  print(' ' ) 0 Kim Found it! 1 in name Ok! else.  ## 예제 2 # error 발생 코드 # error가 발생했어도 except로 잡아냈기 때문에 else 구문을 출력된다. # 그리고, 그 다음 코드를 계속해서 실행한다. print('pass')가 출력된 걸 확인할 수 있다. # 또한, 예제 1에서의 ValueError를 지웠기 때문에 모든 Error를 잡아낸다. # 하지만, 그래서 어떤 Error를 잡았는지 정확히 알 수 없다.  name = ['Kim', 'Lee', 'Park']  try:  z = 'Cho'  x = name.index(z)  print('{} Found it! {} in name'.format(z, x + 1)) # except Exception:  except:  print('Not found it! - Occurred Error!')  else:  print('Ok! else.')   print('pass') Not found it! - Occurred Error! pass  ## 예제 3 # 예제 2를 보완한 코드   name = ['Kim', 'Lee', 'Park']  try:  z = 'Cho'  x = name.index(z)  print('{} Found it! {} in name'.format(z, x + 1)) # 예제 2와 달리 추가된 부분  except Exception as e:  print(e) #  print('Not found it! - Occurred Error!')  else:  print('Ok! else.') # 예외 유무에 상관없이 finally는 실행된다.  finally:  print('Ok! finally') 'Cho' is not in list Not found it! - Occurred Error! Ok! finally  error 를 일부러 발생시킨 경우를 생각해보자. 언제 일부러 error 를 발생시킬까?? 여기서 error 란 Python에서 발생시킨 게 아니라, 설계자가 회사에서 요구하는 논리상 알기 위해서 일부러 발생시킨 error를 말한다. 아래 코드로 설명을 하자면 a가 ‘Kim’이 아니라면 이는 파이썬 내에 ValueError가 발생된 것이 아니다. 하지만 회사에서 ‘Kim’이 아닌 경우에 대해 알기 위해서 error를 발생시켰다. 이를 토대로 언제 ‘Kim’이 아닌지 역으로 분석할 수 있다.  ## error 발생 X  name = ['Kim', 'Lee', 'Park']  try:  a = 'Park'  if a == 'Park':  print('OK! Pass!')  else:  raise ValueError  except ValueError:  print('Occurred! Exception!')  else:  print('Ok! else!') OK! Pass! Ok! else!   ## error 발생 O  name = ['Kim', 'Lee', 'Park']  try:  a = 'Park'  if a == 'Kim':  print('OK! Pass!')  else:  raise ValueError  except ValueError:  print('Occurred! Exception!')  else:  print('Ok! else!') Occurred! Exception!  a에는 ‘Park’가 할당되었다. ‘Kim’이 아니기 때문에, 일부러 ValueError를 발생시켰다. 그래서 except ValueError 문이 실행이 되어 print문이 출력되었다. 일부러 Error를 일으키고, ErrorType도 정할 수 있다는 걸 알고 있자.   Reference  프로그래밍 시작하기: 파이썬 입문 (Inflearn Original)  ","wordCount":"1011","inLanguage":"en","datePublished":"2022-03-03T01:33:28+09:00","dateModified":"2022-03-03T01:33:28+09:00","author":{"@type":"Person","name":"Jeha00"},"mainEntityOfPage":{"@type":"WebPage","@id":"http://jeha00.github.io/post/python_basic/python_basic_17_try_exception/"},"publisher":{"@type":"Organization","name":"Jeha00 DevLog","logo":{"@type":"ImageObject","url":"http://jeha00.github.io/favicon.ico"}}}</script></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=http://jeha00.github.io/ accesskey=h title="Jeha00 (Alt + H)">Jeha00</a>
<span class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)"><svg id="moon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg><svg id="sun" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button></span></div><ul id=menu><li><a href=http://jeha00.github.io/archives/ title=Archive><span>Archive</span></a></li><li><a href=http://jeha00.github.io/categories/ title=Categories><span>Categories</span></a></li><li><a href=http://jeha00.github.io/tags/ title=Tags><span>Tags</span></a></li><li><a href=http://jeha00.github.io/search/ title="Search (Alt + /)" accesskey=/><span>Search</span></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><div class=breadcrumbs><a href=http://jeha00.github.io/>Home</a>&nbsp;»&nbsp;<a href=http://jeha00.github.io/post/>Posts</a></div><h1 class=post-title>[TIL] Python basic 17: try ~ exception</h1><div class=post-meta><span title="2022-03-03 01:33:28 +0900 KST">March 3, 2022</span>&nbsp;·&nbsp;5 min&nbsp;·&nbsp;Jeha00&nbsp;|&nbsp;<a href=https://github.com/JeHa00/blog/content/post/Python_basic/Python_basic_17_try_exception.md rel="noopener noreferrer" target=_blank>Suggest Changes</a></div></header><div class=toc><details><summary accesskey=c title="(Alt + C)"><span class=details>Table of Contents</span></summary><div class=inner><ul><li><a href=#1-exception%ec%98%88%ec%99%b8-and-error%ec%97%90%eb%9f%ac%ec%9d%98-%ec%b0%a8%ec%9d%b4%ec%a0%90 aria-label="1. Exception(예외) and Error(에러)의 차이점">1. Exception(예외) and Error(에러)의 차이점</a></li><li><a href=#2-error%ec%9d%98-%ec%a2%85%eb%a5%98 aria-label="2. Error의 종류">2. Error의 종류</a><ul><li><a href=#21-syntaxerror-%eb%ac%b8%eb%b2%95-%ec%98%a4%eb%a5%98 aria-label="2.1 SyntaxError: 문법 오류">2.1 SyntaxError: 문법 오류</a></li><li><a href=#22-typeerror-%ec%9e%90%eb%a3%8c%ed%98%95%ec%97%90-%eb%a7%9e%ec%a7%80-%ec%95%8a%eb%8a%94-%ec%97%b0%ec%82%b0%ec%9d%84-%ec%88%98%ed%96%89%ed%95%98%ec%97%ac-%eb%b0%9c%ec%83%9d%ed%95%98%eb%8a%94-%ec%98%a4%eb%a5%98 aria-label="2.2 TypeError: 자료형에 맞지 않는 연산을 수행하여 발생하는 오류">2.2 TypeError: 자료형에 맞지 않는 연산을 수행하여 발생하는 오류</a></li><li><a href=#23-nameerror-%ec%b0%b8%ec%a1%b0%ea%b0%80-%ec%97%86%ec%9d%84-%eb%95%8c-%eb%b0%9c%ec%83%9d%ed%95%98%eb%8a%94-%ec%98%a4%eb%a5%98 aria-label="2.3 NameError: 참조가 없을 때 발생하는 오류">2.3 NameError: 참조가 없을 때 발생하는 오류</a></li><li><a href=#24-indexerror-index%ea%b0%80-%ec%a1%b4%ec%9e%ac%ed%95%98%ec%a7%80-%ec%95%8a%ec%95%84-%eb%b0%9c%ec%83%9d%ed%95%98%eb%8a%94-%ec%98%a4%eb%a5%98 aria-label="2.4 IndexError: index가 존재하지 않아 발생하는 오류">2.4 IndexError: index가 존재하지 않아 발생하는 오류</a></li><li><a href=#25-valueerror-%ec%b0%b8%ec%a1%b0%ea%b0%92%ec%9d%b4-%ec%97%86%ec%9d%84-%eb%95%8c-%eb%b0%9c%ec%83%9d%ed%95%98%eb%8a%94-%ec%98%a4%eb%a5%98 aria-label="2.5 ValueError: 참조값이 없을 때 발생하는 오류">2.5 ValueError: 참조값이 없을 때 발생하는 오류</a></li><li><a href=#26-keyerror-%ed%95%b4%eb%8b%b9%eb%90%98%eb%8a%94-key%ea%b0%80-%ec%97%86%ec%9d%84-%eb%95%8c-%eb%b0%9c%ec%83%9d%ed%95%98%eb%8a%94-%ec%98%a4%eb%a5%98 aria-label="2.6 KeyError: 해당되는 key가 없을 때 발생하는 오류">2.6 KeyError: 해당되는 key가 없을 때 발생하는 오류</a></li><li><a href=#27-attributeerror-%eb%aa%a8%eb%93%88-%ed%81%b4%eb%9e%98%ec%8a%a4%ec%97%90-%ec%9e%88%eb%8a%94-%ec%9e%98%eb%aa%bb%eb%90%9c-%ec%86%8d%ec%84%b1%ec%9d%84-%ec%82%ac%ec%9a%a9%ed%95%98%ec%97%ac-%eb%b0%9c%ec%83%9d%ed%95%9c-%ec%98%a4%eb%a5%98 aria-label="2.7 AttributeError: 모듈, 클래스에 있는 잘못된 속성을 사용하여 발생한 오류">2.7 AttributeError: 모듈, 클래스에 있는 잘못된 속성을 사용하여 발생한 오류</a></li><li><a href=#28-filenotfounderror-%ed%8c%8c%ec%9d%bc%ec%9d%84-%ec%b0%be%ec%9d%84-%ec%88%98-%ec%97%86%ec%9d%84-%eb%95%8c-%eb%b0%9c%ec%83%9d%ed%95%98%eb%8a%94-%ec%98%a4%eb%a5%98 aria-label="2.8 FileNotFoundError: 파일을 찾을 수 없을 때 발생하는 오류">2.8 FileNotFoundError: 파일을 찾을 수 없을 때 발생하는 오류</a></li><li><a href=#29-zerodivisionerror-0%ec%9c%bc%eb%a1%9c-%eb%82%98%eb%88%a0%ec%84%9c-%eb%b0%9c%ec%83%9d%ed%95%98%eb%8a%94-%ec%98%a4%eb%a5%98 aria-label="2.9 ZeroDivisionError: 0으로 나눠서 발생하는 오류">2.9 ZeroDivisionError: 0으로 나눠서 발생하는 오류</a></li></ul></li><li><a href=#3-%ec%98%88%ec%99%b8-%ec%b2%98%eb%a6%ac-try--exception aria-label="3. 예외 처리 (try ~ exception)">3. 예외 처리 (try ~ exception)</a></li><li><a href=#reference aria-label=Reference>Reference</a></li></ul></div></details></div><div class=post-content><h2 id=1-exception예외-and-error에러의-차이점>1. Exception(예외) and Error(에러)의 차이점<a hidden class=anchor aria-hidden=true href=#1-exception예외-and-error에러의-차이점>#</a></h2><ul><li><code>Exception(예외)</code> 와 <code>Error(에러)</code>에 대해 설명하겠다.</li><li>예외는 무엇이고 에러는 무엇이다라고 외우진 말자.</li><li>예외를 에러의 범주에 포함하기도 하기 때문이다. 다만, 예외와 에러에 대한 틀을 잡기 위해 설명한다.</li></ul><ul><li><code>Exception(예외)</code>는 우리가 작성한 로직에서 비정상적으로 발생한 사건(event)이다.<ul><li>예외에는 <code>예측이 가능한 예외</code>와 <code>예측이 불가능한 예외</code>로 나눠진다.</li><li><code>예측 가능한 예외</code>의 경우는 <code>id 입력</code>을 생각해보자. 영어로 입력해야하는데, 한글을 입력했을 경우 예외가 발생한다.</li><li><code>예측 불가능한 예외</code>의 경우는 <code>메모리의 용량</code>이 부족해서, <code>OS</code>에서 발생한 에러, 하드웨어적인 에러 등등이 해당된다.</li></ul></li><li>이 예외와 에러를 잘 처리해야 내가 의도한대로 작동하는 어플리케이션을 만들 수 있다.</li></ul><hr><h2 id=2-error의-종류>2. Error의 종류<a hidden class=anchor aria-hidden=true href=#2-error의-종류>#</a></h2><h3 id=21-syntaxerror-문법-오류>2.1 SyntaxError: 문법 오류<a hidden class=anchor aria-hidden=true href=#21-syntaxerror-문법-오류>#</a></h3><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#282a36;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-yml data-lang=yml><span style=display:flex><span><span style=color:#6272a4># 조건문의 헤더에 콜론(:)을 하지 않아 발생했다.</span>
</span></span><span style=display:flex><span>&gt; print(&#39;error&#39;)
</span></span><span style=display:flex><span>&gt; print(&#39;error&#39;)
</span></span><span style=display:flex><span>&gt; if True
</span></span><span style=display:flex><span>&gt;     pass
</span></span><span style=display:flex><span><span style=color:#ff79c6>SyntaxError</span>: invalid syntax
</span></span></code></pre></div><h3 id=22-typeerror-자료형에-맞지-않는-연산을-수행하여-발생하는-오류>2.2 TypeError: 자료형에 맞지 않는 연산을 수행하여 발생하는 오류<a hidden class=anchor aria-hidden=true href=#22-typeerror-자료형에-맞지-않는-연산을-수행하여-발생하는-오류>#</a></h3><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#282a36;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-yml data-lang=yml><span style=display:flex><span>&gt; x = [1,2]
</span></span><span style=display:flex><span>&gt; y = (1,2)
</span></span><span style=display:flex><span>&gt; z = &#39;test&#39;
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#6272a4># list와 tuple은 합칠 수 없다.</span>
</span></span><span style=display:flex><span>&gt; print(x + y)
</span></span><span style=display:flex><span><span style=color:#ff79c6>TypeError</span>: can only concatenate list (not &#34;tuple&#34;) to list
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#6272a4># string과 list는 합칠 수 없다.</span>
</span></span><span style=display:flex><span>&gt; print(x + z)
</span></span><span style=display:flex><span><span style=color:#ff79c6>TypeError</span>: can only concatenate list (not &#34;str&#34;) to list
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#6272a4># tuple과 string은 합칠 수 없다.</span>
</span></span><span style=display:flex><span>&gt; print(y + z)
</span></span><span style=display:flex><span><span style=color:#ff79c6>TypeError</span>: can only concatenate list (not &#34;str&#34;) to list
</span></span></code></pre></div><h3 id=23-nameerror-참조가-없을-때-발생하는-오류>2.3 NameError: 참조가 없을 때 발생하는 오류<a hidden class=anchor aria-hidden=true href=#23-nameerror-참조가-없을-때-발생하는-오류>#</a></h3><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#282a36;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-yml data-lang=yml><span style=display:flex><span>&gt; a = 10
</span></span><span style=display:flex><span>&gt; b = 15
</span></span><span style=display:flex><span>&gt; print(c)
</span></span><span style=display:flex><span><span style=color:#ff79c6>NameError</span>: name &#39;c&#39; is not defined
</span></span></code></pre></div><h3 id=24-indexerror-index가-존재하지-않아-발생하는-오류>2.4 IndexError: index가 존재하지 않아 발생하는 오류<a hidden class=anchor aria-hidden=true href=#24-indexerror-index가-존재하지-않아-발생하는-오류>#</a></h3><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#282a36;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-yml data-lang=yml><span style=display:flex><span>&gt; x = [50, 70, 90]
</span></span><span style=display:flex><span>&gt; print(x[1])
</span></span><span style=display:flex><span><span style=color:#bd93f9>70</span>
</span></span><span style=display:flex><span>&gt; print(x[4]
</span></span><span style=display:flex><span><span style=color:#ff79c6>IndexError</span>: list index out of range
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#6272a4># 알고리즘에서 op을 사용할 때 발생할 수 있는 에러</span>
</span></span><span style=display:flex><span>&gt; print(x.pop())
</span></span><span style=display:flex><span><span style=color:#bd93f9>50</span>
</span></span><span style=display:flex><span>&gt; print(x.pop())
</span></span><span style=display:flex><span><span style=color:#bd93f9>70</span>
</span></span><span style=display:flex><span>&gt; print(x.pop())
</span></span><span style=display:flex><span><span style=color:#bd93f9>90</span>
</span></span><span style=display:flex><span>&gt; print(x.pop())
</span></span><span style=display:flex><span><span style=color:#ff79c6>IndexError</span>: pop from empty list
</span></span></code></pre></div><h3 id=25-valueerror-참조값이-없을-때-발생하는-오류>2.5 ValueError: 참조값이 없을 때 발생하는 오류<a hidden class=anchor aria-hidden=true href=#25-valueerror-참조값이-없을-때-발생하는-오류>#</a></h3><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#282a36;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-yml data-lang=yml><span style=display:flex><span>&gt; x = [10, 50, 90]
</span></span><span style=display:flex><span>&gt; x.remove(50)
</span></span><span style=display:flex><span>&gt; print(x)
</span></span><span style=display:flex><span>[<span style=color:#bd93f9>10</span>, <span style=color:#bd93f9>90</span>]
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>&gt; x.remove(200)
</span></span><span style=display:flex><span><span style=color:#ff79c6>ValueError: list.remove(x)</span>: x not in list
</span></span></code></pre></div><h3 id=26-keyerror-해당되는-key가-없을-때-발생하는-오류>2.6 KeyError: 해당되는 key가 없을 때 발생하는 오류<a hidden class=anchor aria-hidden=true href=#26-keyerror-해당되는-key가-없을-때-발생하는-오류>#</a></h3><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#282a36;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-yml data-lang=yml><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#6272a4># `key` 값으로 `value` 값을 출력할 때는 `.get()` 함수를 사용한다.</span>
</span></span><span style=display:flex><span>&gt; x = {&#39;A&#39;: &#39;apple&#39;, &#39;B&#39;: &#39;Banana&#39;, &#39;C&#39;: &#39;coffee&#39;}
</span></span><span style=display:flex><span>&gt; print(x[&#39;D&#39;])
</span></span><span style=display:flex><span><span style=color:#ff79c6>KeyError</span>: <span style=color:#f1fa8c>&#39;D&#39;</span>
</span></span><span style=display:flex><span>&gt; print(x.get(&#39;D&#39;))
</span></span><span style=display:flex><span>None
</span></span></code></pre></div><h3 id=27-attributeerror-모듈-클래스에-있는-잘못된-속성을-사용하여-발생한-오류>2.7 AttributeError: 모듈, 클래스에 있는 잘못된 속성을 사용하여 발생한 오류<a hidden class=anchor aria-hidden=true href=#27-attributeerror-모듈-클래스에-있는-잘못된-속성을-사용하여-발생한-오류>#</a></h3><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#282a36;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-yml data-lang=yml><span style=display:flex><span>&gt; import time
</span></span><span style=display:flex><span>&gt;  print(time.time2())
</span></span><span style=display:flex><span><span style=color:#ff79c6>AttributeError</span>: module &#39;time&#39; has no attribute &#39;time2&#39;
</span></span></code></pre></div><h3 id=28-filenotfounderror-파일을-찾을-수-없을-때-발생하는-오류>2.8 FileNotFoundError: 파일을 찾을 수 없을 때 발생하는 오류<a hidden class=anchor aria-hidden=true href=#28-filenotfounderror-파일을-찾을-수-없을-때-발생하는-오류>#</a></h3><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#282a36;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-yml data-lang=yml><span style=display:flex><span>&gt; f = open(&#39;test.txt&#39;)
</span></span><span style=display:flex><span><span style=color:#ff79c6>FileNotFoundError: [Errno 2] No such file or directory</span>: <span style=color:#f1fa8c>&#39;test.txt&#39;</span>
</span></span></code></pre></div><h3 id=29-zerodivisionerror-0으로-나눠서-발생하는-오류>2.9 ZeroDivisionError: 0으로 나눠서 발생하는 오류<a hidden class=anchor aria-hidden=true href=#29-zerodivisionerror-0으로-나눠서-발생하는-오류>#</a></h3><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#282a36;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-yml data-lang=yml><span style=display:flex><span>&gt; print(100 / 0)
</span></span><span style=display:flex><span><span style=color:#ff79c6>ZeroDivisionError</span>: division by zero
</span></span></code></pre></div><hr><h2 id=3-예외-처리-try--exception>3. 예외 처리 (try ~ exception)<a hidden class=anchor aria-hidden=true href=#3-예외-처리-try--exception>#</a></h2><ul><li><code>try</code>: <code>에러가 발생할 가능성이 있는 코드</code> 실행<ul><li>이 에러는 내 코드가 정확해도, 방문한 사이트 서버나 여러 프로그램이 외부와 연결될 때, 문제가 있을 수 있기 때문이다. 그래서 외부적으로 문제가 발생해도 <code>try ~ except</code>로 대비한다.</li></ul></li><li><code>except 에러명 1~n</code>:<ul><li>error가 발생했을 때 잡아내어 다음 코드로 넘어가도록 해준다.</li><li>여러 개 가능하다.</li><li>어떤 Error만 잡을지 정할 수 있다.</li><li>모든 error 잡아내기<ul><li><code>except Exception:</code>은 모든 예외의 부모격이라 모든 error를 잡아낸다.</li><li><code>except:</code> 또한, 모든 error을 잡아낸다.</li><li>하지만, 정확히 어떤 error가 발생했는지 알 수 없다.</li><li>정확히 어떤 error가 발생했는지 알아야 로그를 남길 때 정확히 남길 수 있다.</li></ul></li><li>예제 3에서처럼 예제 2에서 <code>alias</code>를 줘서 <code>except Exception as e</code> 와 <code>print(e)</code> 을 사용하여, 대략적인 error 내용을 확인하여 출력하도록 할 수 있다.</li></ul></li><li><code>else</code>: <code>try block</code>에 <code>에러</code>가 <code>없을 경우</code> 실행한다.<ul><li>정상적으로 흘러갈 때 실행된다.</li><li><code>for ~ else</code> 에서도 <code>for</code>문에 <code>break</code>를 만나지 않으면 <code>else</code>가 실행했듯이, <code>except</code>를 만나지 않으면 실행된다.</li></ul></li><li><code>finally</code>: 에러발생 유무와 상관없이 <code>무조건</code> 실행된다.<ul><li>error 발생 유무에 상관없이 항상 실행해줘야 하는 구문으로 <code>finally</code>를 사용한다.</li><li>예를 들어 error가 발생했을 경우, 연결된 메모리를 끊어줘야 메모리가 새지 않기 때문에 <code>finally</code>를 통해서 실행한다.</li></ul></li></ul><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#282a36;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-yml data-lang=yml><span style=display:flex><span><span style=color:#6272a4>## 예제 1</span>
</span></span><span style=display:flex><span><span style=color:#6272a4>## error 발생하지 않는 코드</span>
</span></span><span style=display:flex><span>&gt; name = [&#39;Kim&#39;, &#39;Lee&#39;, &#39;Park&#39;]
</span></span><span style=display:flex><span>&gt; print(name.index(&#39;Kim&#39;))
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt; try </span>:
</span></span><span style=display:flex><span>&gt;      z = &#39;Kim&#39;
</span></span><span style=display:flex><span>&gt;      x = name.index(z)
</span></span><span style=display:flex><span>&gt;      print(&#39;{} Found it! {} in name&#39;.format(z, x + 1))
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#6272a4># error 중 ValueError 만 잡는다.</span>
</span></span><span style=display:flex><span><span style=color:#6272a4># error 처리 시, 이렇게 error의 정확한 유형대로 잡아내느 것이 제일 좋은 case다.</span>
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt; except ValueError</span>:
</span></span><span style=display:flex><span>&gt;      print(&#39;Not found it! - Occurred ValueError!&#39;)
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#6272a4># error가 발생되지 않았으므로 else 구문이 작동된다.</span>
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt; else</span>:
</span></span><span style=display:flex><span>&gt;      print(&#39;Ok! else.&#39;)
</span></span><span style=display:flex><span>&gt; print(&#39; &#39; )
</span></span><span style=display:flex><span><span style=color:#bd93f9>0</span>
</span></span><span style=display:flex><span>Kim Found it! 1 in name
</span></span><span style=display:flex><span>Ok! else.
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#6272a4>## 예제 2</span>
</span></span><span style=display:flex><span><span style=color:#6272a4># error 발생 코드</span>
</span></span><span style=display:flex><span><span style=color:#6272a4># error가 발생했어도 except로 잡아냈기 때문에 else 구문을 출력된다.</span>
</span></span><span style=display:flex><span><span style=color:#6272a4># 그리고, 그 다음 코드를 계속해서 실행한다. print(&#39;pass&#39;)가 출력된 걸 확인할 수 있다.</span>
</span></span><span style=display:flex><span><span style=color:#6272a4># 또한, 예제 1에서의 ValueError를 지웠기 때문에 모든 Error를 잡아낸다.</span>
</span></span><span style=display:flex><span><span style=color:#6272a4># 하지만, 그래서 어떤 Error를 잡았는지 정확히 알 수 없다.</span>
</span></span><span style=display:flex><span>&gt; name = [&#39;Kim&#39;, &#39;Lee&#39;, &#39;Park&#39;]
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt; try</span>:
</span></span><span style=display:flex><span>&gt;      z = &#39;Cho&#39;
</span></span><span style=display:flex><span>&gt;      x = name.index(z)
</span></span><span style=display:flex><span>&gt;      print(&#39;{} Found it! {} in name&#39;.format(z, x + 1))
</span></span><span style=display:flex><span><span style=color:#6272a4>#  except Exception:</span>
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;  except</span>:
</span></span><span style=display:flex><span>&gt;      print(&#39;Not found it! - Occurred Error!&#39;)
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;  else</span>:
</span></span><span style=display:flex><span>&gt;      print(&#39;Ok! else.&#39;)
</span></span><span style=display:flex><span>&gt;
</span></span><span style=display:flex><span>&gt; print(&#39;pass&#39;)
</span></span><span style=display:flex><span>Not found it! - Occurred Error!
</span></span><span style=display:flex><span>pass
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#6272a4>## 예제 3</span>
</span></span><span style=display:flex><span><span style=color:#6272a4># 예제 2를 보완한 코드</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>&gt; name = [&#39;Kim&#39;, &#39;Lee&#39;, &#39;Park&#39;]
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt; try</span>:
</span></span><span style=display:flex><span>&gt;     z = &#39;Cho&#39;
</span></span><span style=display:flex><span>&gt;     x = name.index(z)
</span></span><span style=display:flex><span>&gt;     print(&#39;{} Found it! {} in name&#39;.format(z, x + 1))
</span></span><span style=display:flex><span><span style=color:#6272a4># 예제 2와 달리 추가된 부분</span>
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt; except Exception as e</span>:
</span></span><span style=display:flex><span>&gt;     print(e)
</span></span><span style=display:flex><span><span style=color:#6272a4>#</span>
</span></span><span style=display:flex><span>&gt;     print(&#39;Not found it! - Occurred Error!&#39;)
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt; else</span>:
</span></span><span style=display:flex><span>&gt;     print(&#39;Ok! else.&#39;)
</span></span><span style=display:flex><span><span style=color:#6272a4># 예외 유무에 상관없이 finally는 실행된다.</span>
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt; finally</span>:
</span></span><span style=display:flex><span>&gt;     print(&#39;Ok! finally&#39;)
</span></span><span style=display:flex><span><span style=color:#f1fa8c>&#39;Cho&#39;</span> is not in list
</span></span><span style=display:flex><span>Not found it! - Occurred Error!
</span></span><span style=display:flex><span>Ok! finally
</span></span></code></pre></div><ul><li><strong>error</strong> 를 일부러 발생시킨 경우를 생각해보자. 언제 일부러 <strong>error</strong> 를 발생시킬까??</li><li>여기서 <strong>error</strong> 란 Python에서 발생시킨 게 아니라, 설계자가 회사에서 요구하는 논리상 알기 위해서 <strong>일부러</strong> 발생시킨 error를 말한다.</li><li>아래 코드로 설명을 하자면 a가 &lsquo;Kim&rsquo;이 아니라면 이는 파이썬 내에 <code>ValueError</code>가 발생된 것이 아니다. 하지만 회사에서 &lsquo;Kim&rsquo;이 아닌 경우에 대해 알기 위해서 error를 발생시켰다. 이를 토대로 언제 &lsquo;Kim&rsquo;이 아닌지 역으로 분석할 수 있다.</li></ul><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#282a36;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-yml data-lang=yml><span style=display:flex><span><span style=color:#6272a4>## error 발생 X</span>
</span></span><span style=display:flex><span>&gt; name = [&#39;Kim&#39;, &#39;Lee&#39;, &#39;Park&#39;]
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;  try</span>:
</span></span><span style=display:flex><span>&gt;      a = &#39;Park&#39;
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;      if a == &#39;Park&#39;</span>:
</span></span><span style=display:flex><span>&gt;          print(&#39;OK! Pass!&#39;)
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;      else</span>:
</span></span><span style=display:flex><span>&gt;          raise ValueError
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;  except ValueError</span>:
</span></span><span style=display:flex><span>&gt;      print(&#39;Occurred! Exception!&#39;)
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;  else</span>:
</span></span><span style=display:flex><span>&gt;      print(&#39;Ok! else!&#39;)
</span></span><span style=display:flex><span>OK! Pass!
</span></span><span style=display:flex><span>Ok! else!
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span><span style=color:#6272a4>## error 발생 O</span>
</span></span><span style=display:flex><span>&gt; name = [&#39;Kim&#39;, &#39;Lee&#39;, &#39;Park&#39;]
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;  try</span>:
</span></span><span style=display:flex><span>&gt;      a = &#39;Park&#39;
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;      if a == &#39;Kim&#39;</span>:
</span></span><span style=display:flex><span>&gt;          print(&#39;OK! Pass!&#39;)
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;      else</span>:
</span></span><span style=display:flex><span>&gt;          raise ValueError
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;  except ValueError</span>:
</span></span><span style=display:flex><span>&gt;      print(&#39;Occurred! Exception!&#39;)
</span></span><span style=display:flex><span><span style=color:#ff79c6>&gt;  else</span>:
</span></span><span style=display:flex><span>&gt;      print(&#39;Ok! else!&#39;)
</span></span><span style=display:flex><span>Occurred! Exception!
</span></span></code></pre></div><ul><li>a에는 &lsquo;Park&rsquo;가 할당되었다. &lsquo;Kim&rsquo;이 아니기 때문에, 일부러 <code>ValueError</code>를 발생시켰다. 그래서 <code>except ValueError</code> 문이 실행이 되어 print문이 출력되었다.</li><li>일부러 Error를 일으키고, ErrorType도 정할 수 있다는 걸 알고 있자.</li></ul><hr><h2 id=reference>Reference<a hidden class=anchor aria-hidden=true href=#reference>#</a></h2><ul><li><a href=https://www.inflearn.com/course/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D-%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%9E%85%EB%AC%B8-%EC%9D%B8%ED%94%84%EB%9F%B0-%EC%98%A4%EB%A6%AC%EC%A7%80%EB%84%90>프로그래밍 시작하기: 파이썬 입문 (Inflearn Original)</a></li></ul></div><footer class=post-footer><ul class=post-tags><li><a href=http://jeha00.github.io/tags/til/>TIL</a></li><li><a href=http://jeha00.github.io/tags/python/>python</a></li></ul><nav class=paginav><a class=prev href=http://jeha00.github.io/post/python_basic/python_basic_18_built_in_fuctions/><span class=title>« Prev Page</span><br><span>[TIL] Python basic 18: built-in functions</span></a>
<a class=next href=http://jeha00.github.io/post/python_basic/python_basic_16_package/><span class=title>Next Page »</span><br><span>[TIL] Python basic 16: package</span></a></nav><div class=share-buttons><a target=_blank rel="noopener noreferrer" aria-label="share [TIL] Python basic 17: try ~ exception on twitter" href="https://twitter.com/intent/tweet/?text=%5bTIL%5d%20Python%20basic%2017%3a%20try%20~%20exception&url=http%3a%2f%2fjeha00.github.io%2fpost%2fpython_basic%2fpython_basic_17_try_exception%2f&hashtags=TIL%2cpython"><svg viewBox="0 0 512 512"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM195.519 424.544c135.939.0 210.268-112.643 210.268-210.268.0-3.218.0-6.437-.153-9.502 14.406-10.421 26.973-23.448 36.935-38.314-13.18 5.824-27.433 9.809-42.452 11.648 15.326-9.196 26.973-23.602 32.49-40.92-14.252 8.429-30.038 14.56-46.896 17.931-13.487-14.406-32.644-23.295-53.946-23.295-40.767.0-73.87 33.104-73.87 73.87.0 5.824.613 11.494 1.992 16.858-61.456-3.065-115.862-32.49-152.337-77.241-6.284 10.881-9.962 23.601-9.962 37.088.0 25.594 13.027 48.276 32.95 61.456-12.107-.307-23.448-3.678-33.41-9.196v.92c0 35.862 25.441 65.594 59.311 72.49-6.13 1.686-12.72 2.606-19.464 2.606-4.751.0-9.348-.46-13.946-1.38 9.349 29.426 36.628 50.728 68.965 51.341-25.287 19.771-57.164 31.571-91.8 31.571-5.977.0-11.801-.306-17.625-1.073 32.337 21.15 71.264 33.41 112.95 33.41z"/></svg></a><a target=_blank rel="noopener noreferrer" aria-label="share [TIL] Python basic 17: try ~ exception on linkedin" href="https://www.linkedin.com/shareArticle?mini=true&url=http%3a%2f%2fjeha00.github.io%2fpost%2fpython_basic%2fpython_basic_17_try_exception%2f&title=%5bTIL%5d%20Python%20basic%2017%3a%20try%20~%20exception&summary=%5bTIL%5d%20Python%20basic%2017%3a%20try%20~%20exception&source=http%3a%2f%2fjeha00.github.io%2fpost%2fpython_basic%2fpython_basic_17_try_exception%2f"><svg viewBox="0 0 512 512"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM160.461 423.278V197.561h-75.04v225.717h75.04zm270.539.0V293.839c0-69.333-37.018-101.586-86.381-101.586-39.804.0-57.634 21.891-67.617 37.266v-31.958h-75.021c.995 21.181.0 225.717.0 225.717h75.02V297.222c0-6.748.486-13.492 2.474-18.315 5.414-13.475 17.767-27.434 38.494-27.434 27.135.0 38.007 20.707 38.007 51.037v120.768H431zM123.448 88.722C97.774 88.722 81 105.601 81 127.724c0 21.658 16.264 39.002 41.455 39.002h.484c26.165.0 42.452-17.344 42.452-39.002-.485-22.092-16.241-38.954-41.943-39.002z"/></svg></a><a target=_blank rel="noopener noreferrer" aria-label="share [TIL] Python basic 17: try ~ exception on reddit" href="https://reddit.com/submit?url=http%3a%2f%2fjeha00.github.io%2fpost%2fpython_basic%2fpython_basic_17_try_exception%2f&title=%5bTIL%5d%20Python%20basic%2017%3a%20try%20~%20exception"><svg viewBox="0 0 512 512"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zM446 265.638c0-22.964-18.616-41.58-41.58-41.58-11.211.0-21.361 4.457-28.841 11.666-28.424-20.508-67.586-33.757-111.204-35.278l18.941-89.121 61.884 13.157c.756 15.734 13.642 28.29 29.56 28.29 16.407.0 29.706-13.299 29.706-29.701.0-16.403-13.299-29.702-29.706-29.702-11.666.0-21.657 6.792-26.515 16.578l-69.105-14.69c-1.922-.418-3.939-.042-5.585 1.036-1.658 1.073-2.811 2.761-3.224 4.686l-21.152 99.438c-44.258 1.228-84.046 14.494-112.837 35.232-7.468-7.164-17.589-11.591-28.757-11.591-22.965.0-41.585 18.616-41.585 41.58.0 16.896 10.095 31.41 24.568 37.918-.639 4.135-.99 8.328-.99 12.576.0 63.977 74.469 115.836 166.33 115.836s166.334-51.859 166.334-115.836c0-4.218-.347-8.387-.977-12.493 14.564-6.47 24.735-21.034 24.735-38.001zM326.526 373.831c-20.27 20.241-59.115 21.816-70.534 21.816-11.428.0-50.277-1.575-70.522-21.82-3.007-3.008-3.007-7.882.0-10.889 3.003-2.999 7.882-3.003 10.885.0 12.777 12.781 40.11 17.317 59.637 17.317 19.522.0 46.86-4.536 59.657-17.321 3.016-2.999 7.886-2.995 10.885.008 3.008 3.011 3.003 7.882-.008 10.889zm-5.23-48.781c-16.373.0-29.701-13.324-29.701-29.698.0-16.381 13.328-29.714 29.701-29.714 16.378.0 29.706 13.333 29.706 29.714.0 16.374-13.328 29.698-29.706 29.698zM160.91 295.348c0-16.381 13.328-29.71 29.714-29.71 16.369.0 29.689 13.329 29.689 29.71.0 16.373-13.32 29.693-29.689 29.693-16.386.0-29.714-13.32-29.714-29.693z"/></svg></a><a target=_blank rel="noopener noreferrer" aria-label="share [TIL] Python basic 17: try ~ exception on facebook" href="https://facebook.com/sharer/sharer.php?u=http%3a%2f%2fjeha00.github.io%2fpost%2fpython_basic%2fpython_basic_17_try_exception%2f"><svg viewBox="0 0 512 512"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H342.978V319.085h66.6l12.672-82.621h-79.272v-53.617c0-22.603 11.073-44.636 46.58-44.636H425.6v-70.34s-32.71-5.582-63.982-5.582c-65.288.0-107.96 39.569-107.96 111.204v62.971h-72.573v82.621h72.573V512h-191.104c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892z"/></svg></a><a target=_blank rel="noopener noreferrer" aria-label="share [TIL] Python basic 17: try ~ exception on whatsapp" href="https://api.whatsapp.com/send?text=%5bTIL%5d%20Python%20basic%2017%3a%20try%20~%20exception%20-%20http%3a%2f%2fjeha00.github.io%2fpost%2fpython_basic%2fpython_basic_17_try_exception%2f"><svg viewBox="0 0 512 512"><path d="M449.446.0C483.971.0 512 28.03 512 62.554v386.892C512 483.97 483.97 512 449.446 512H62.554c-34.524.0-62.554-28.03-62.554-62.554V62.554c0-34.524 28.029-62.554 62.554-62.554h386.892zm-58.673 127.703c-33.842-33.881-78.847-52.548-126.798-52.568-98.799.0-179.21 80.405-179.249 179.234-.013 31.593 8.241 62.428 23.927 89.612l-25.429 92.884 95.021-24.925c26.181 14.28 55.659 21.807 85.658 21.816h.074c98.789.0 179.206-80.413 179.247-179.243.018-47.895-18.61-92.93-52.451-126.81zM263.976 403.485h-.06c-26.734-.01-52.954-7.193-75.828-20.767l-5.441-3.229-56.386 14.792 15.05-54.977-3.542-5.637c-14.913-23.72-22.791-51.136-22.779-79.287.033-82.142 66.867-148.971 149.046-148.971 39.793.014 77.199 15.531 105.329 43.692 28.128 28.16 43.609 65.592 43.594 105.4-.034 82.149-66.866 148.983-148.983 148.984zm81.721-111.581c-4.479-2.242-26.499-13.075-30.604-14.571-4.105-1.495-7.091-2.241-10.077 2.241-2.986 4.483-11.569 14.572-14.182 17.562-2.612 2.988-5.225 3.364-9.703 1.12-4.479-2.241-18.91-6.97-36.017-22.23C231.8 264.15 222.81 249.484 220.198 245s-.279-6.908 1.963-9.14c2.016-2.007 4.48-5.232 6.719-7.847 2.24-2.615 2.986-4.484 4.479-7.472 1.493-2.99.747-5.604-.374-7.846-1.119-2.241-10.077-24.288-13.809-33.256-3.635-8.733-7.327-7.55-10.077-7.688-2.609-.13-5.598-.158-8.583-.158-2.986.0-7.839 1.121-11.944 5.604-4.105 4.484-15.675 15.32-15.675 37.364.0 22.046 16.048 43.342 18.287 46.332 2.24 2.99 31.582 48.227 76.511 67.627 10.685 4.615 19.028 7.371 25.533 9.434 10.728 3.41 20.492 2.929 28.209 1.775 8.605-1.285 26.499-10.833 30.231-21.295 3.732-10.464 3.732-19.431 2.612-21.298-1.119-1.869-4.105-2.99-8.583-5.232z"/></svg></a><a target=_blank rel="noopener noreferrer" aria-label="share [TIL] Python basic 17: try ~ exception on telegram" href="https://telegram.me/share/url?text=%5bTIL%5d%20Python%20basic%2017%3a%20try%20~%20exception&url=http%3a%2f%2fjeha00.github.io%2fpost%2fpython_basic%2fpython_basic_17_try_exception%2f"><svg viewBox="2 2 28 28"><path d="M26.49 29.86H5.5a3.37 3.37.0 01-2.47-1 3.35 3.35.0 01-1-2.47V5.48A3.36 3.36.0 013 3 3.37 3.37.0 015.5 2h21A3.38 3.38.0 0129 3a3.36 3.36.0 011 2.46V26.37a3.35 3.35.0 01-1 2.47 3.38 3.38.0 01-2.51 1.02zm-5.38-6.71a.79.79.0 00.85-.66L24.73 9.24a.55.55.0 00-.18-.46.62.62.0 00-.41-.17q-.08.0-16.53 6.11a.59.59.0 00-.41.59.57.57.0 00.43.52l4 1.24 1.61 4.83a.62.62.0 00.63.43.56.56.0 00.4-.17L16.54 20l4.09 3A.9.9.0 0021.11 23.15zM13.8 20.71l-1.21-4q8.72-5.55 8.78-5.55c.15.0.23.0.23.16a.18.18.0 010 .06s-2.51 2.3-7.52 6.8z"/></svg></a></div></footer><script src=https://utteranc.es/client.js repo=JeHa00/blog-comments issue-term=pathname theme=github-dark crossorigin=anonymous async></script></article></main><footer class=footer><span>&copy; 2022 <a href=http://jeha00.github.io/>Jeha00 DevLog</a></span>
<span>Powered by
<a href=https://gohugo.io/ rel="noopener noreferrer" target=_blank>Hugo</a> &
        <a href=https://git.io/hugopapermod rel=noopener target=_blank>PaperMod</a></span></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6" fill="currentcolor"><path d="M12 6H0l6-6z"/></svg></a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(t){t.preventDefault();var e=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(e)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(e)}']`).scrollIntoView({behavior:"smooth"}),e==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${e}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script></body></html>